/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GUESTFS_PROTOCOL_H_RPCGEN
#define _GUESTFS_PROTOCOL_H_RPCGEN

#include <config.h>

#include "guestfs_protocol.pb-c.h"
#include "guestfs_protocol_typedefs.h"


#endif /* !_GUESTFS_PROTOCOL_H_RPCGEN */
