/* libguestfs generated file -*- c -*-
 * WARNING: THIS FILE IS GENERATED FROM:
 *   generator/ *.ml
 * ANY CHANGES YOU MAKE TO THIS FILE WILL BE LOST.
 *
 * Copyright (C) 2009-2015 Red Hat Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef _GUESTFS_PROTOBUF_PROTOCOL_TYPEDEFS_H_
#define _GUESTFS_PROTOBUF_PROTOCOL_TYPEDEFS_H_


/* Internal structures. */

typedef GuestfsProtobufIntIntBool guestfs_protobuf_int_int_bool;
typedef GuestfsProtobufIntIntBoolList guestfs_protobuf_int_int_bool_list;

typedef GuestfsProtobufIntLvmPv guestfs_protobuf_int_lvm_pv;
typedef GuestfsProtobufIntLvmPvList guestfs_protobuf_int_lvm_pv_list;

typedef GuestfsProtobufIntLvmVg guestfs_protobuf_int_lvm_vg;
typedef GuestfsProtobufIntLvmVgList guestfs_protobuf_int_lvm_vg_list;

typedef GuestfsProtobufIntLvmLv guestfs_protobuf_int_lvm_lv;
typedef GuestfsProtobufIntLvmLvList guestfs_protobuf_int_lvm_lv_list;

typedef GuestfsProtobufIntStat guestfs_protobuf_int_stat;
typedef GuestfsProtobufIntStatList guestfs_protobuf_int_stat_list;

typedef GuestfsProtobufIntStatns guestfs_protobuf_int_statns;
typedef GuestfsProtobufIntStatnsList guestfs_protobuf_int_statns_list;

typedef GuestfsProtobufIntStatvfs guestfs_protobuf_int_statvfs;
typedef GuestfsProtobufIntStatvfsList guestfs_protobuf_int_statvfs_list;

typedef GuestfsProtobufIntDirent guestfs_protobuf_int_dirent;
typedef GuestfsProtobufIntDirentList guestfs_protobuf_int_dirent_list;

typedef GuestfsProtobufIntVersion guestfs_protobuf_int_version;
typedef GuestfsProtobufIntVersionList guestfs_protobuf_int_version_list;

typedef GuestfsProtobufIntXattr guestfs_protobuf_int_xattr;
typedef GuestfsProtobufIntXattrList guestfs_protobuf_int_xattr_list;

typedef GuestfsProtobufIntInotifyEvent guestfs_protobuf_int_inotify_event;
typedef GuestfsProtobufIntInotifyEventList guestfs_protobuf_int_inotify_event_list;

typedef GuestfsProtobufIntPartition guestfs_protobuf_int_partition;
typedef GuestfsProtobufIntPartitionList guestfs_protobuf_int_partition_list;

typedef GuestfsProtobufIntApplication guestfs_protobuf_int_application;
typedef GuestfsProtobufIntApplicationList guestfs_protobuf_int_application_list;

typedef GuestfsProtobufIntApplication2 guestfs_protobuf_int_application2;
typedef GuestfsProtobufIntApplication2List guestfs_protobuf_int_application2_list;

typedef GuestfsProtobufIntIsoinfo guestfs_protobuf_int_isoinfo;
typedef GuestfsProtobufIntIsoinfoList guestfs_protobuf_int_isoinfo_list;

typedef GuestfsProtobufIntMdstat guestfs_protobuf_int_mdstat;
typedef GuestfsProtobufIntMdstatList guestfs_protobuf_int_mdstat_list;

typedef GuestfsProtobufIntBtrfssubvolume guestfs_protobuf_int_btrfssubvolume;
typedef GuestfsProtobufIntBtrfssubvolumeList guestfs_protobuf_int_btrfssubvolume_list;

typedef GuestfsProtobufIntXfsinfo guestfs_protobuf_int_xfsinfo;
typedef GuestfsProtobufIntXfsinfoList guestfs_protobuf_int_xfsinfo_list;

typedef GuestfsProtobufIntUtsname guestfs_protobuf_int_utsname;
typedef GuestfsProtobufIntUtsnameList guestfs_protobuf_int_utsname_list;

typedef GuestfsProtobufIntHivexNode guestfs_protobuf_int_hivex_node;
typedef GuestfsProtobufIntHivexNodeList guestfs_protobuf_int_hivex_node_list;

typedef GuestfsProtobufIntHivexValue guestfs_protobuf_int_hivex_value;
typedef GuestfsProtobufIntHivexValueList guestfs_protobuf_int_hivex_value_list;

typedef GuestfsProtobufIntInternalMountable guestfs_protobuf_int_internal_mountable;
typedef GuestfsProtobufIntInternalMountableList guestfs_protobuf_int_internal_mountable_list;

/* Function arguments and return values. */

typedef GuestfsProtobufMountArgs guestfs_protobuf_mount_args;

typedef GuestfsProtobufTouchArgs guestfs_protobuf_touch_args;

typedef GuestfsProtobufLlArgs guestfs_protobuf_ll_args;

typedef GuestfsProtobufLlRet guestfs_protobuf_ll_ret;

typedef GuestfsProtobufListDevicesRet guestfs_protobuf_list_devices_ret;

typedef GuestfsProtobufListPartitionsRet guestfs_protobuf_list_partitions_ret;

typedef GuestfsProtobufPvsRet guestfs_protobuf_pvs_ret;

typedef GuestfsProtobufVgsRet guestfs_protobuf_vgs_ret;

typedef GuestfsProtobufLvsRet guestfs_protobuf_lvs_ret;

typedef GuestfsProtobufPvsFullRet guestfs_protobuf_pvs_full_ret;

typedef GuestfsProtobufVgsFullRet guestfs_protobuf_vgs_full_ret;

typedef GuestfsProtobufLvsFullRet guestfs_protobuf_lvs_full_ret;

typedef GuestfsProtobufAugInitArgs guestfs_protobuf_aug_init_args;

typedef GuestfsProtobufAugDefvarArgs guestfs_protobuf_aug_defvar_args;

typedef GuestfsProtobufAugDefvarRet guestfs_protobuf_aug_defvar_ret;

typedef GuestfsProtobufAugDefnodeArgs guestfs_protobuf_aug_defnode_args;

typedef GuestfsProtobufAugDefnodeRet guestfs_protobuf_aug_defnode_ret;

typedef GuestfsProtobufAugGetArgs guestfs_protobuf_aug_get_args;

typedef GuestfsProtobufAugGetRet guestfs_protobuf_aug_get_ret;

typedef GuestfsProtobufAugSetArgs guestfs_protobuf_aug_set_args;

typedef GuestfsProtobufAugInsertArgs guestfs_protobuf_aug_insert_args;

typedef GuestfsProtobufAugRmArgs guestfs_protobuf_aug_rm_args;

typedef GuestfsProtobufAugRmRet guestfs_protobuf_aug_rm_ret;

typedef GuestfsProtobufAugMvArgs guestfs_protobuf_aug_mv_args;

typedef GuestfsProtobufAugMatchArgs guestfs_protobuf_aug_match_args;

typedef GuestfsProtobufAugMatchRet guestfs_protobuf_aug_match_ret;

typedef GuestfsProtobufAugLsArgs guestfs_protobuf_aug_ls_args;

typedef GuestfsProtobufAugLsRet guestfs_protobuf_aug_ls_ret;

typedef GuestfsProtobufRmArgs guestfs_protobuf_rm_args;

typedef GuestfsProtobufRmdirArgs guestfs_protobuf_rmdir_args;

typedef GuestfsProtobufRmRfArgs guestfs_protobuf_rm_rf_args;

typedef GuestfsProtobufMkdirArgs guestfs_protobuf_mkdir_args;

typedef GuestfsProtobufMkdirPpArgs guestfs_protobuf_mkdir_pp_args;

typedef GuestfsProtobufChmodArgs guestfs_protobuf_chmod_args;

typedef GuestfsProtobufChownArgs guestfs_protobuf_chown_args;

typedef GuestfsProtobufExistsArgs guestfs_protobuf_exists_args;

typedef GuestfsProtobufExistsRet guestfs_protobuf_exists_ret;

typedef GuestfsProtobufIsFileArgs guestfs_protobuf_is_file_args;

typedef GuestfsProtobufIsFileRet guestfs_protobuf_is_file_ret;

typedef GuestfsProtobufIsDirArgs guestfs_protobuf_is_dir_args;

typedef GuestfsProtobufIsDirRet guestfs_protobuf_is_dir_ret;

typedef GuestfsProtobufPvcreateArgs guestfs_protobuf_pvcreate_args;

typedef GuestfsProtobufVgcreateArgs guestfs_protobuf_vgcreate_args;

typedef GuestfsProtobufLvcreateArgs guestfs_protobuf_lvcreate_args;

typedef GuestfsProtobufSfdiskArgs guestfs_protobuf_sfdisk_args;

typedef GuestfsProtobufWriteFileArgs guestfs_protobuf_write_file_args;

typedef GuestfsProtobufUmountArgs guestfs_protobuf_umount_args;

typedef GuestfsProtobufMountsRet guestfs_protobuf_mounts_ret;

typedef GuestfsProtobufFileArgs guestfs_protobuf_file_args;

typedef GuestfsProtobufFileRet guestfs_protobuf_file_ret;

typedef GuestfsProtobufCommandArgs guestfs_protobuf_command_args;

typedef GuestfsProtobufCommandRet guestfs_protobuf_command_ret;

typedef GuestfsProtobufCommandLinesArgs guestfs_protobuf_command_lines_args;

typedef GuestfsProtobufCommandLinesRet guestfs_protobuf_command_lines_ret;

typedef GuestfsProtobufStatvfsArgs guestfs_protobuf_statvfs_args;

typedef GuestfsProtobufStatvfsRet guestfs_protobuf_statvfs_ret;

typedef GuestfsProtobufTune2fsLlArgs guestfs_protobuf_tune2fs_ll_args;

typedef GuestfsProtobufTune2fsLlRet guestfs_protobuf_tune2fs_ll_ret;

typedef GuestfsProtobufBlockdevSetroArgs guestfs_protobuf_blockdev_setro_args;

typedef GuestfsProtobufBlockdevSetrwArgs guestfs_protobuf_blockdev_setrw_args;

typedef GuestfsProtobufBlockdevGetroArgs guestfs_protobuf_blockdev_getro_args;

typedef GuestfsProtobufBlockdevGetroRet guestfs_protobuf_blockdev_getro_ret;

typedef GuestfsProtobufBlockdevGetssArgs guestfs_protobuf_blockdev_getss_args;

typedef GuestfsProtobufBlockdevGetssRet guestfs_protobuf_blockdev_getss_ret;

typedef GuestfsProtobufBlockdevGetbszArgs guestfs_protobuf_blockdev_getbsz_args;

typedef GuestfsProtobufBlockdevGetbszRet guestfs_protobuf_blockdev_getbsz_ret;

typedef GuestfsProtobufBlockdevSetbszArgs guestfs_protobuf_blockdev_setbsz_args;

typedef GuestfsProtobufBlockdevGetszArgs guestfs_protobuf_blockdev_getsz_args;

typedef GuestfsProtobufBlockdevGetszRet guestfs_protobuf_blockdev_getsz_ret;

typedef GuestfsProtobufBlockdevGetsize64Args guestfs_protobuf_blockdev_getsize64_args;

typedef GuestfsProtobufBlockdevGetsize64Ret guestfs_protobuf_blockdev_getsize64_ret;

typedef GuestfsProtobufBlockdevFlushbufsArgs guestfs_protobuf_blockdev_flushbufs_args;

typedef GuestfsProtobufBlockdevRereadptArgs guestfs_protobuf_blockdev_rereadpt_args;

typedef GuestfsProtobufUploadArgs guestfs_protobuf_upload_args;

typedef GuestfsProtobufDownloadArgs guestfs_protobuf_download_args;

typedef GuestfsProtobufChecksumArgs guestfs_protobuf_checksum_args;

typedef GuestfsProtobufChecksumRet guestfs_protobuf_checksum_ret;

typedef GuestfsProtobufTarInArgs guestfs_protobuf_tar_in_args;

typedef GuestfsProtobufTarOutArgs guestfs_protobuf_tar_out_args;

typedef GuestfsProtobufTgzInArgs guestfs_protobuf_tgz_in_args;

typedef GuestfsProtobufTgzOutArgs guestfs_protobuf_tgz_out_args;

typedef GuestfsProtobufMountRoArgs guestfs_protobuf_mount_ro_args;

typedef GuestfsProtobufMountOptionsArgs guestfs_protobuf_mount_options_args;

typedef GuestfsProtobufMountVfsArgs guestfs_protobuf_mount_vfs_args;

typedef GuestfsProtobufDebugArgs guestfs_protobuf_debug_args;

typedef GuestfsProtobufDebugRet guestfs_protobuf_debug_ret;

typedef GuestfsProtobufLvremoveArgs guestfs_protobuf_lvremove_args;

typedef GuestfsProtobufVgremoveArgs guestfs_protobuf_vgremove_args;

typedef GuestfsProtobufPvremoveArgs guestfs_protobuf_pvremove_args;

typedef GuestfsProtobufSetE2labelArgs guestfs_protobuf_set_e2label_args;

typedef GuestfsProtobufGetE2labelArgs guestfs_protobuf_get_e2label_args;

typedef GuestfsProtobufGetE2labelRet guestfs_protobuf_get_e2label_ret;

typedef GuestfsProtobufSetE2uuidArgs guestfs_protobuf_set_e2uuid_args;

typedef GuestfsProtobufGetE2uuidArgs guestfs_protobuf_get_e2uuid_args;

typedef GuestfsProtobufGetE2uuidRet guestfs_protobuf_get_e2uuid_ret;

typedef GuestfsProtobufFsckArgs guestfs_protobuf_fsck_args;

typedef GuestfsProtobufFsckRet guestfs_protobuf_fsck_ret;

typedef GuestfsProtobufZeroArgs guestfs_protobuf_zero_args;

typedef GuestfsProtobufGrubInstallArgs guestfs_protobuf_grub_install_args;

typedef GuestfsProtobufCpArgs guestfs_protobuf_cp_args;

typedef GuestfsProtobufCpAaArgs guestfs_protobuf_cp_aa_args;

typedef GuestfsProtobufMvArgs guestfs_protobuf_mv_args;

typedef GuestfsProtobufDropCachesArgs guestfs_protobuf_drop_caches_args;

typedef GuestfsProtobufDmesgRet guestfs_protobuf_dmesg_ret;

typedef GuestfsProtobufEqualArgs guestfs_protobuf_equal_args;

typedef GuestfsProtobufEqualRet guestfs_protobuf_equal_ret;

typedef GuestfsProtobufStringsArgs guestfs_protobuf_strings_args;

typedef GuestfsProtobufStringsRet guestfs_protobuf_strings_ret;

typedef GuestfsProtobufStringsEeArgs guestfs_protobuf_strings_ee_args;

typedef GuestfsProtobufStringsEeRet guestfs_protobuf_strings_ee_ret;

typedef GuestfsProtobufHexdumpArgs guestfs_protobuf_hexdump_args;

typedef GuestfsProtobufHexdumpRet guestfs_protobuf_hexdump_ret;

typedef GuestfsProtobufZerofreeArgs guestfs_protobuf_zerofree_args;

typedef GuestfsProtobufPvresizeArgs guestfs_protobuf_pvresize_args;

typedef GuestfsProtobufSfdiskNnArgs guestfs_protobuf_sfdisk_nn_args;

typedef GuestfsProtobufSfdiskLlArgs guestfs_protobuf_sfdisk_ll_args;

typedef GuestfsProtobufSfdiskLlRet guestfs_protobuf_sfdisk_ll_ret;

typedef GuestfsProtobufSfdiskKernelGeometryArgs guestfs_protobuf_sfdisk_kernel_geometry_args;

typedef GuestfsProtobufSfdiskKernelGeometryRet guestfs_protobuf_sfdisk_kernel_geometry_ret;

typedef GuestfsProtobufSfdiskDiskGeometryArgs guestfs_protobuf_sfdisk_disk_geometry_args;

typedef GuestfsProtobufSfdiskDiskGeometryRet guestfs_protobuf_sfdisk_disk_geometry_ret;

typedef GuestfsProtobufVgActivateAllArgs guestfs_protobuf_vg_activate_all_args;

typedef GuestfsProtobufVgActivateArgs guestfs_protobuf_vg_activate_args;

typedef GuestfsProtobufLvresizeArgs guestfs_protobuf_lvresize_args;

typedef GuestfsProtobufResize2fsArgs guestfs_protobuf_resize2fs_args;

typedef GuestfsProtobufE2fsckFfArgs guestfs_protobuf_e2fsck_ff_args;

typedef GuestfsProtobufSleepArgs guestfs_protobuf_sleep_args;

typedef GuestfsProtobufNtfs3gProbeArgs guestfs_protobuf_ntfs3g_probe_args;

typedef GuestfsProtobufNtfs3gProbeRet guestfs_protobuf_ntfs3g_probe_ret;

typedef GuestfsProtobufShArgs guestfs_protobuf_sh_args;

typedef GuestfsProtobufShRet guestfs_protobuf_sh_ret;

typedef GuestfsProtobufShLinesArgs guestfs_protobuf_sh_lines_args;

typedef GuestfsProtobufShLinesRet guestfs_protobuf_sh_lines_ret;

typedef GuestfsProtobufGlobExpandArgs guestfs_protobuf_glob_expand_args;

typedef GuestfsProtobufGlobExpandRet guestfs_protobuf_glob_expand_ret;

typedef GuestfsProtobufScrubDeviceArgs guestfs_protobuf_scrub_device_args;

typedef GuestfsProtobufScrubFileArgs guestfs_protobuf_scrub_file_args;

typedef GuestfsProtobufScrubFreespaceArgs guestfs_protobuf_scrub_freespace_args;

typedef GuestfsProtobufMkdtempArgs guestfs_protobuf_mkdtemp_args;

typedef GuestfsProtobufMkdtempRet guestfs_protobuf_mkdtemp_ret;

typedef GuestfsProtobufWcLlArgs guestfs_protobuf_wc_ll_args;

typedef GuestfsProtobufWcLlRet guestfs_protobuf_wc_ll_ret;

typedef GuestfsProtobufWcWwArgs guestfs_protobuf_wc_ww_args;

typedef GuestfsProtobufWcWwRet guestfs_protobuf_wc_ww_ret;

typedef GuestfsProtobufWcCcArgs guestfs_protobuf_wc_cc_args;

typedef GuestfsProtobufWcCcRet guestfs_protobuf_wc_cc_ret;

typedef GuestfsProtobufHeadArgs guestfs_protobuf_head_args;

typedef GuestfsProtobufHeadRet guestfs_protobuf_head_ret;

typedef GuestfsProtobufHeadNnArgs guestfs_protobuf_head_nn_args;

typedef GuestfsProtobufHeadNnRet guestfs_protobuf_head_nn_ret;

typedef GuestfsProtobufTailArgs guestfs_protobuf_tail_args;

typedef GuestfsProtobufTailRet guestfs_protobuf_tail_ret;

typedef GuestfsProtobufTailNnArgs guestfs_protobuf_tail_nn_args;

typedef GuestfsProtobufTailNnRet guestfs_protobuf_tail_nn_ret;

typedef GuestfsProtobufDfRet guestfs_protobuf_df_ret;

typedef GuestfsProtobufDfHhRet guestfs_protobuf_df_hh_ret;

typedef GuestfsProtobufDuArgs guestfs_protobuf_du_args;

typedef GuestfsProtobufDuRet guestfs_protobuf_du_ret;

typedef GuestfsProtobufInitrdListArgs guestfs_protobuf_initrd_list_args;

typedef GuestfsProtobufInitrdListRet guestfs_protobuf_initrd_list_ret;

typedef GuestfsProtobufMountLoopArgs guestfs_protobuf_mount_loop_args;

typedef GuestfsProtobufMkswapArgs guestfs_protobuf_mkswap_args;

typedef GuestfsProtobufMkswapLlArgs guestfs_protobuf_mkswap_ll_args;

typedef GuestfsProtobufMkswapUuArgs guestfs_protobuf_mkswap_uu_args;

typedef GuestfsProtobufMknodArgs guestfs_protobuf_mknod_args;

typedef GuestfsProtobufMkfifoArgs guestfs_protobuf_mkfifo_args;

typedef GuestfsProtobufMknodBbArgs guestfs_protobuf_mknod_bb_args;

typedef GuestfsProtobufMknodCcArgs guestfs_protobuf_mknod_cc_args;

typedef GuestfsProtobufUmaskArgs guestfs_protobuf_umask_args;

typedef GuestfsProtobufUmaskRet guestfs_protobuf_umask_ret;

typedef GuestfsProtobufReaddirArgs guestfs_protobuf_readdir_args;

typedef GuestfsProtobufReaddirRet guestfs_protobuf_readdir_ret;

typedef GuestfsProtobufSfdiskmArgs guestfs_protobuf_sfdiskm_args;

typedef GuestfsProtobufZfileArgs guestfs_protobuf_zfile_args;

typedef GuestfsProtobufZfileRet guestfs_protobuf_zfile_ret;

typedef GuestfsProtobufGetxattrsArgs guestfs_protobuf_getxattrs_args;

typedef GuestfsProtobufGetxattrsRet guestfs_protobuf_getxattrs_ret;

typedef GuestfsProtobufLgetxattrsArgs guestfs_protobuf_lgetxattrs_args;

typedef GuestfsProtobufLgetxattrsRet guestfs_protobuf_lgetxattrs_ret;

typedef GuestfsProtobufSetxattrArgs guestfs_protobuf_setxattr_args;

typedef GuestfsProtobufLsetxattrArgs guestfs_protobuf_lsetxattr_args;

typedef GuestfsProtobufRemovexattrArgs guestfs_protobuf_removexattr_args;

typedef GuestfsProtobufLremovexattrArgs guestfs_protobuf_lremovexattr_args;

typedef GuestfsProtobufMountpointsRet guestfs_protobuf_mountpoints_ret;

typedef GuestfsProtobufMkmountpointArgs guestfs_protobuf_mkmountpoint_args;

typedef GuestfsProtobufRmmountpointArgs guestfs_protobuf_rmmountpoint_args;

typedef GuestfsProtobufGrepArgs guestfs_protobuf_grep_args;

typedef GuestfsProtobufGrepRet guestfs_protobuf_grep_ret;

typedef GuestfsProtobufEgrepArgs guestfs_protobuf_egrep_args;

typedef GuestfsProtobufEgrepRet guestfs_protobuf_egrep_ret;

typedef GuestfsProtobufFgrepArgs guestfs_protobuf_fgrep_args;

typedef GuestfsProtobufFgrepRet guestfs_protobuf_fgrep_ret;

typedef GuestfsProtobufGrepiArgs guestfs_protobuf_grepi_args;

typedef GuestfsProtobufGrepiRet guestfs_protobuf_grepi_ret;

typedef GuestfsProtobufEgrepiArgs guestfs_protobuf_egrepi_args;

typedef GuestfsProtobufEgrepiRet guestfs_protobuf_egrepi_ret;

typedef GuestfsProtobufFgrepiArgs guestfs_protobuf_fgrepi_args;

typedef GuestfsProtobufFgrepiRet guestfs_protobuf_fgrepi_ret;

typedef GuestfsProtobufZgrepArgs guestfs_protobuf_zgrep_args;

typedef GuestfsProtobufZgrepRet guestfs_protobuf_zgrep_ret;

typedef GuestfsProtobufZegrepArgs guestfs_protobuf_zegrep_args;

typedef GuestfsProtobufZegrepRet guestfs_protobuf_zegrep_ret;

typedef GuestfsProtobufZfgrepArgs guestfs_protobuf_zfgrep_args;

typedef GuestfsProtobufZfgrepRet guestfs_protobuf_zfgrep_ret;

typedef GuestfsProtobufZgrepiArgs guestfs_protobuf_zgrepi_args;

typedef GuestfsProtobufZgrepiRet guestfs_protobuf_zgrepi_ret;

typedef GuestfsProtobufZegrepiArgs guestfs_protobuf_zegrepi_args;

typedef GuestfsProtobufZegrepiRet guestfs_protobuf_zegrepi_ret;

typedef GuestfsProtobufZfgrepiArgs guestfs_protobuf_zfgrepi_args;

typedef GuestfsProtobufZfgrepiRet guestfs_protobuf_zfgrepi_ret;

typedef GuestfsProtobufRealpathArgs guestfs_protobuf_realpath_args;

typedef GuestfsProtobufRealpathRet guestfs_protobuf_realpath_ret;

typedef GuestfsProtobufLnArgs guestfs_protobuf_ln_args;

typedef GuestfsProtobufLnFfArgs guestfs_protobuf_ln_ff_args;

typedef GuestfsProtobufLnSsArgs guestfs_protobuf_ln_ss_args;

typedef GuestfsProtobufLnSfArgs guestfs_protobuf_ln_sf_args;

typedef GuestfsProtobufReadlinkArgs guestfs_protobuf_readlink_args;

typedef GuestfsProtobufReadlinkRet guestfs_protobuf_readlink_ret;

typedef GuestfsProtobufFallocateArgs guestfs_protobuf_fallocate_args;

typedef GuestfsProtobufSwaponDeviceArgs guestfs_protobuf_swapon_device_args;

typedef GuestfsProtobufSwapoffDeviceArgs guestfs_protobuf_swapoff_device_args;

typedef GuestfsProtobufSwaponFileArgs guestfs_protobuf_swapon_file_args;

typedef GuestfsProtobufSwapoffFileArgs guestfs_protobuf_swapoff_file_args;

typedef GuestfsProtobufSwaponLabelArgs guestfs_protobuf_swapon_label_args;

typedef GuestfsProtobufSwapoffLabelArgs guestfs_protobuf_swapoff_label_args;

typedef GuestfsProtobufSwaponUuidArgs guestfs_protobuf_swapon_uuid_args;

typedef GuestfsProtobufSwapoffUuidArgs guestfs_protobuf_swapoff_uuid_args;

typedef GuestfsProtobufMkswapFileArgs guestfs_protobuf_mkswap_file_args;

typedef GuestfsProtobufInotifyInitArgs guestfs_protobuf_inotify_init_args;

typedef GuestfsProtobufInotifyAddWatchArgs guestfs_protobuf_inotify_add_watch_args;

typedef GuestfsProtobufInotifyAddWatchRet guestfs_protobuf_inotify_add_watch_ret;

typedef GuestfsProtobufInotifyRmWatchArgs guestfs_protobuf_inotify_rm_watch_args;

typedef GuestfsProtobufInotifyReadRet guestfs_protobuf_inotify_read_ret;

typedef GuestfsProtobufInotifyFilesRet guestfs_protobuf_inotify_files_ret;

typedef GuestfsProtobufSetconArgs guestfs_protobuf_setcon_args;

typedef GuestfsProtobufGetconRet guestfs_protobuf_getcon_ret;

typedef GuestfsProtobufMkfsBbArgs guestfs_protobuf_mkfs_bb_args;

typedef GuestfsProtobufMke2journalArgs guestfs_protobuf_mke2journal_args;

typedef GuestfsProtobufMke2journalLlArgs guestfs_protobuf_mke2journal_ll_args;

typedef GuestfsProtobufMke2journalUuArgs guestfs_protobuf_mke2journal_uu_args;

typedef GuestfsProtobufMke2fsJjArgs guestfs_protobuf_mke2fs_jj_args;

typedef GuestfsProtobufMke2fsJlArgs guestfs_protobuf_mke2fs_jl_args;

typedef GuestfsProtobufMke2fsJuArgs guestfs_protobuf_mke2fs_ju_args;

typedef GuestfsProtobufModprobeArgs guestfs_protobuf_modprobe_args;

typedef GuestfsProtobufEchoDaemonArgs guestfs_protobuf_echo_daemon_args;

typedef GuestfsProtobufEchoDaemonRet guestfs_protobuf_echo_daemon_ret;

typedef GuestfsProtobufFind0Args guestfs_protobuf_find0_args;

typedef GuestfsProtobufCaseSensitivePathArgs guestfs_protobuf_case_sensitive_path_args;

typedef GuestfsProtobufCaseSensitivePathRet guestfs_protobuf_case_sensitive_path_ret;

typedef GuestfsProtobufVfsTypeArgs guestfs_protobuf_vfs_type_args;

typedef GuestfsProtobufVfsTypeRet guestfs_protobuf_vfs_type_ret;

typedef GuestfsProtobufTruncateArgs guestfs_protobuf_truncate_args;

typedef GuestfsProtobufTruncateSizeArgs guestfs_protobuf_truncate_size_args;

typedef GuestfsProtobufUtimensArgs guestfs_protobuf_utimens_args;

typedef GuestfsProtobufMkdirModeArgs guestfs_protobuf_mkdir_mode_args;

typedef GuestfsProtobufLchownArgs guestfs_protobuf_lchown_args;

typedef GuestfsProtobufInternalLxattrlistArgs guestfs_protobuf_internal_lxattrlist_args;

typedef GuestfsProtobufInternalLxattrlistRet guestfs_protobuf_internal_lxattrlist_ret;

typedef GuestfsProtobufInternalReadlinklistArgs guestfs_protobuf_internal_readlinklist_args;

typedef GuestfsProtobufInternalReadlinklistRet guestfs_protobuf_internal_readlinklist_ret;

typedef GuestfsProtobufPreadArgs guestfs_protobuf_pread_args;

typedef GuestfsProtobufPreadRet guestfs_protobuf_pread_ret;

typedef GuestfsProtobufPartInitArgs guestfs_protobuf_part_init_args;

typedef GuestfsProtobufPartAddArgs guestfs_protobuf_part_add_args;

typedef GuestfsProtobufPartDiskArgs guestfs_protobuf_part_disk_args;

typedef GuestfsProtobufPartSetBootableArgs guestfs_protobuf_part_set_bootable_args;

typedef GuestfsProtobufPartSetNameArgs guestfs_protobuf_part_set_name_args;

typedef GuestfsProtobufPartListArgs guestfs_protobuf_part_list_args;

typedef GuestfsProtobufPartListRet guestfs_protobuf_part_list_ret;

typedef GuestfsProtobufPartGetParttypeArgs guestfs_protobuf_part_get_parttype_args;

typedef GuestfsProtobufPartGetParttypeRet guestfs_protobuf_part_get_parttype_ret;

typedef GuestfsProtobufFillArgs guestfs_protobuf_fill_args;

typedef GuestfsProtobufAvailableArgs guestfs_protobuf_available_args;

typedef GuestfsProtobufDdArgs guestfs_protobuf_dd_args;

typedef GuestfsProtobufFilesizeArgs guestfs_protobuf_filesize_args;

typedef GuestfsProtobufFilesizeRet guestfs_protobuf_filesize_ret;

typedef GuestfsProtobufLvrenameArgs guestfs_protobuf_lvrename_args;

typedef GuestfsProtobufVgrenameArgs guestfs_protobuf_vgrename_args;

typedef GuestfsProtobufInitrdCatArgs guestfs_protobuf_initrd_cat_args;

typedef GuestfsProtobufInitrdCatRet guestfs_protobuf_initrd_cat_ret;

typedef GuestfsProtobufPvuuidArgs guestfs_protobuf_pvuuid_args;

typedef GuestfsProtobufPvuuidRet guestfs_protobuf_pvuuid_ret;

typedef GuestfsProtobufVguuidArgs guestfs_protobuf_vguuid_args;

typedef GuestfsProtobufVguuidRet guestfs_protobuf_vguuid_ret;

typedef GuestfsProtobufLvuuidArgs guestfs_protobuf_lvuuid_args;

typedef GuestfsProtobufLvuuidRet guestfs_protobuf_lvuuid_ret;

typedef GuestfsProtobufVgpvuuidsArgs guestfs_protobuf_vgpvuuids_args;

typedef GuestfsProtobufVgpvuuidsRet guestfs_protobuf_vgpvuuids_ret;

typedef GuestfsProtobufVglvuuidsArgs guestfs_protobuf_vglvuuids_args;

typedef GuestfsProtobufVglvuuidsRet guestfs_protobuf_vglvuuids_ret;

typedef GuestfsProtobufCopySizeArgs guestfs_protobuf_copy_size_args;

typedef GuestfsProtobufZeroDeviceArgs guestfs_protobuf_zero_device_args;

typedef GuestfsProtobufTxzInArgs guestfs_protobuf_txz_in_args;

typedef GuestfsProtobufTxzOutArgs guestfs_protobuf_txz_out_args;

typedef GuestfsProtobufPartDelArgs guestfs_protobuf_part_del_args;

typedef GuestfsProtobufPartGetBootableArgs guestfs_protobuf_part_get_bootable_args;

typedef GuestfsProtobufPartGetBootableRet guestfs_protobuf_part_get_bootable_ret;

typedef GuestfsProtobufPartGetMbrIdArgs guestfs_protobuf_part_get_mbr_id_args;

typedef GuestfsProtobufPartGetMbrIdRet guestfs_protobuf_part_get_mbr_id_ret;

typedef GuestfsProtobufPartSetMbrIdArgs guestfs_protobuf_part_set_mbr_id_args;

typedef GuestfsProtobufChecksumDeviceArgs guestfs_protobuf_checksum_device_args;

typedef GuestfsProtobufChecksumDeviceRet guestfs_protobuf_checksum_device_ret;

typedef GuestfsProtobufLvresizeFreeArgs guestfs_protobuf_lvresize_free_args;

typedef GuestfsProtobufAugClearArgs guestfs_protobuf_aug_clear_args;

typedef GuestfsProtobufGetUmaskRet guestfs_protobuf_get_umask_ret;

typedef GuestfsProtobufDebugUploadArgs guestfs_protobuf_debug_upload_args;

typedef GuestfsProtobufBase64InArgs guestfs_protobuf_base64_in_args;

typedef GuestfsProtobufBase64OutArgs guestfs_protobuf_base64_out_args;

typedef GuestfsProtobufChecksumsOutArgs guestfs_protobuf_checksums_out_args;

typedef GuestfsProtobufFillPatternArgs guestfs_protobuf_fill_pattern_args;

typedef GuestfsProtobufInternalWriteArgs guestfs_protobuf_internal_write_args;

typedef GuestfsProtobufPwriteArgs guestfs_protobuf_pwrite_args;

typedef GuestfsProtobufPwriteRet guestfs_protobuf_pwrite_ret;

typedef GuestfsProtobufResize2fsSizeArgs guestfs_protobuf_resize2fs_size_args;

typedef GuestfsProtobufPvresizeSizeArgs guestfs_protobuf_pvresize_size_args;

typedef GuestfsProtobufNtfsresizeSizeArgs guestfs_protobuf_ntfsresize_size_args;

typedef GuestfsProtobufAvailableAllGroupsRet guestfs_protobuf_available_all_groups_ret;

typedef GuestfsProtobufFallocate64Args guestfs_protobuf_fallocate64_args;

typedef GuestfsProtobufVfsLabelArgs guestfs_protobuf_vfs_label_args;

typedef GuestfsProtobufVfsLabelRet guestfs_protobuf_vfs_label_ret;

typedef GuestfsProtobufVfsUuidArgs guestfs_protobuf_vfs_uuid_args;

typedef GuestfsProtobufVfsUuidRet guestfs_protobuf_vfs_uuid_ret;

typedef GuestfsProtobufLvmSetFilterArgs guestfs_protobuf_lvm_set_filter_args;

typedef GuestfsProtobufLuksOpenArgs guestfs_protobuf_luks_open_args;

typedef GuestfsProtobufLuksOpenRoArgs guestfs_protobuf_luks_open_ro_args;

typedef GuestfsProtobufLuksCloseArgs guestfs_protobuf_luks_close_args;

typedef GuestfsProtobufLuksFormatArgs guestfs_protobuf_luks_format_args;

typedef GuestfsProtobufLuksFormatCipherArgs guestfs_protobuf_luks_format_cipher_args;

typedef GuestfsProtobufLuksAddKeyArgs guestfs_protobuf_luks_add_key_args;

typedef GuestfsProtobufLuksKillSlotArgs guestfs_protobuf_luks_kill_slot_args;

typedef GuestfsProtobufIsLvArgs guestfs_protobuf_is_lv_args;

typedef GuestfsProtobufIsLvRet guestfs_protobuf_is_lv_ret;

typedef GuestfsProtobufFindfsUuidArgs guestfs_protobuf_findfs_uuid_args;

typedef GuestfsProtobufFindfsUuidRet guestfs_protobuf_findfs_uuid_ret;

typedef GuestfsProtobufFindfsLabelArgs guestfs_protobuf_findfs_label_args;

typedef GuestfsProtobufFindfsLabelRet guestfs_protobuf_findfs_label_ret;

typedef GuestfsProtobufIsChardevArgs guestfs_protobuf_is_chardev_args;

typedef GuestfsProtobufIsChardevRet guestfs_protobuf_is_chardev_ret;

typedef GuestfsProtobufIsBlockdevArgs guestfs_protobuf_is_blockdev_args;

typedef GuestfsProtobufIsBlockdevRet guestfs_protobuf_is_blockdev_ret;

typedef GuestfsProtobufIsFifoArgs guestfs_protobuf_is_fifo_args;

typedef GuestfsProtobufIsFifoRet guestfs_protobuf_is_fifo_ret;

typedef GuestfsProtobufIsSymlinkArgs guestfs_protobuf_is_symlink_args;

typedef GuestfsProtobufIsSymlinkRet guestfs_protobuf_is_symlink_ret;

typedef GuestfsProtobufIsSocketArgs guestfs_protobuf_is_socket_args;

typedef GuestfsProtobufIsSocketRet guestfs_protobuf_is_socket_ret;

typedef GuestfsProtobufPartToDevArgs guestfs_protobuf_part_to_dev_args;

typedef GuestfsProtobufPartToDevRet guestfs_protobuf_part_to_dev_ret;

typedef GuestfsProtobufUploadOffsetArgs guestfs_protobuf_upload_offset_args;

typedef GuestfsProtobufDownloadOffsetArgs guestfs_protobuf_download_offset_args;

typedef GuestfsProtobufPwriteDeviceArgs guestfs_protobuf_pwrite_device_args;

typedef GuestfsProtobufPwriteDeviceRet guestfs_protobuf_pwrite_device_ret;

typedef GuestfsProtobufPreadDeviceArgs guestfs_protobuf_pread_device_args;

typedef GuestfsProtobufPreadDeviceRet guestfs_protobuf_pread_device_ret;

typedef GuestfsProtobufLvmCanonicalLvNameArgs guestfs_protobuf_lvm_canonical_lv_name_args;

typedef GuestfsProtobufLvmCanonicalLvNameRet guestfs_protobuf_lvm_canonical_lv_name_ret;

typedef GuestfsProtobufMkfsArgs guestfs_protobuf_mkfs_args;

typedef GuestfsProtobufGetxattrArgs guestfs_protobuf_getxattr_args;

typedef GuestfsProtobufGetxattrRet guestfs_protobuf_getxattr_ret;

typedef GuestfsProtobufLgetxattrArgs guestfs_protobuf_lgetxattr_args;

typedef GuestfsProtobufLgetxattrRet guestfs_protobuf_lgetxattr_ret;

typedef GuestfsProtobufResize2fsMmArgs guestfs_protobuf_resize2fs_mm_args;

typedef GuestfsProtobufIsZeroArgs guestfs_protobuf_is_zero_args;

typedef GuestfsProtobufIsZeroRet guestfs_protobuf_is_zero_ret;

typedef GuestfsProtobufIsZeroDeviceArgs guestfs_protobuf_is_zero_device_args;

typedef GuestfsProtobufIsZeroDeviceRet guestfs_protobuf_is_zero_device_ret;

typedef GuestfsProtobufList9pRet guestfs_protobuf_list9p_ret;

typedef GuestfsProtobufMount9pArgs guestfs_protobuf_mount9p_args;

typedef GuestfsProtobufListDmDevicesRet guestfs_protobuf_list_dm_devices_ret;

typedef GuestfsProtobufNtfsresizeArgs guestfs_protobuf_ntfsresize_args;

typedef GuestfsProtobufBtrfsFilesystemResizeArgs guestfs_protobuf_btrfs_filesystem_resize_args;

typedef GuestfsProtobufInternalWriteAppendArgs guestfs_protobuf_internal_write_append_args;

typedef GuestfsProtobufCompressOutArgs guestfs_protobuf_compress_out_args;

typedef GuestfsProtobufCompressDeviceOutArgs guestfs_protobuf_compress_device_out_args;

typedef GuestfsProtobufPartToPartnumArgs guestfs_protobuf_part_to_partnum_args;

typedef GuestfsProtobufPartToPartnumRet guestfs_protobuf_part_to_partnum_ret;

typedef GuestfsProtobufCopyDeviceToDeviceArgs guestfs_protobuf_copy_device_to_device_args;

typedef GuestfsProtobufCopyDeviceToFileArgs guestfs_protobuf_copy_device_to_file_args;

typedef GuestfsProtobufCopyFileToDeviceArgs guestfs_protobuf_copy_file_to_device_args;

typedef GuestfsProtobufCopyFileToFileArgs guestfs_protobuf_copy_file_to_file_args;

typedef GuestfsProtobufTune2fsArgs guestfs_protobuf_tune2fs_args;

typedef GuestfsProtobufMdCreateArgs guestfs_protobuf_md_create_args;

typedef GuestfsProtobufListMdDevicesRet guestfs_protobuf_list_md_devices_ret;

typedef GuestfsProtobufMdDetailArgs guestfs_protobuf_md_detail_args;

typedef GuestfsProtobufMdDetailRet guestfs_protobuf_md_detail_ret;

typedef GuestfsProtobufMdStopArgs guestfs_protobuf_md_stop_args;

typedef GuestfsProtobufBlkidArgs guestfs_protobuf_blkid_args;

typedef GuestfsProtobufBlkidRet guestfs_protobuf_blkid_ret;

typedef GuestfsProtobufE2fsckArgs guestfs_protobuf_e2fsck_args;

typedef GuestfsProtobufLlzArgs guestfs_protobuf_llz_args;

typedef GuestfsProtobufLlzRet guestfs_protobuf_llz_ret;

typedef GuestfsProtobufWipefsArgs guestfs_protobuf_wipefs_args;

typedef GuestfsProtobufNtfsfixArgs guestfs_protobuf_ntfsfix_args;

typedef GuestfsProtobufNtfscloneOutArgs guestfs_protobuf_ntfsclone_out_args;

typedef GuestfsProtobufNtfscloneInArgs guestfs_protobuf_ntfsclone_in_args;

typedef GuestfsProtobufSetLabelArgs guestfs_protobuf_set_label_args;

typedef GuestfsProtobufZeroFreeSpaceArgs guestfs_protobuf_zero_free_space_args;

typedef GuestfsProtobufLvcreateFreeArgs guestfs_protobuf_lvcreate_free_args;

typedef GuestfsProtobufIsoinfoDeviceArgs guestfs_protobuf_isoinfo_device_args;

typedef GuestfsProtobufIsoinfoDeviceRet guestfs_protobuf_isoinfo_device_ret;

typedef GuestfsProtobufIsoinfoArgs guestfs_protobuf_isoinfo_args;

typedef GuestfsProtobufIsoinfoRet guestfs_protobuf_isoinfo_ret;

typedef GuestfsProtobufVgmetaArgs guestfs_protobuf_vgmeta_args;

typedef GuestfsProtobufVgmetaRet guestfs_protobuf_vgmeta_ret;

typedef GuestfsProtobufMdStatArgs guestfs_protobuf_md_stat_args;

typedef GuestfsProtobufMdStatRet guestfs_protobuf_md_stat_ret;

typedef GuestfsProtobufMkfsBtrfsArgs guestfs_protobuf_mkfs_btrfs_args;

typedef GuestfsProtobufGetE2attrsArgs guestfs_protobuf_get_e2attrs_args;

typedef GuestfsProtobufGetE2attrsRet guestfs_protobuf_get_e2attrs_ret;

typedef GuestfsProtobufSetE2attrsArgs guestfs_protobuf_set_e2attrs_args;

typedef GuestfsProtobufGetE2generationArgs guestfs_protobuf_get_e2generation_args;

typedef GuestfsProtobufGetE2generationRet guestfs_protobuf_get_e2generation_ret;

typedef GuestfsProtobufSetE2generationArgs guestfs_protobuf_set_e2generation_args;

typedef GuestfsProtobufBtrfsSubvolumeSnapshotArgs guestfs_protobuf_btrfs_subvolume_snapshot_args;

typedef GuestfsProtobufBtrfsSubvolumeDeleteArgs guestfs_protobuf_btrfs_subvolume_delete_args;

typedef GuestfsProtobufBtrfsSubvolumeCreateArgs guestfs_protobuf_btrfs_subvolume_create_args;

typedef GuestfsProtobufBtrfsSubvolumeListArgs guestfs_protobuf_btrfs_subvolume_list_args;

typedef GuestfsProtobufBtrfsSubvolumeListRet guestfs_protobuf_btrfs_subvolume_list_ret;

typedef GuestfsProtobufBtrfsSubvolumeSetDefaultArgs guestfs_protobuf_btrfs_subvolume_set_default_args;

typedef GuestfsProtobufBtrfsFilesystemSyncArgs guestfs_protobuf_btrfs_filesystem_sync_args;

typedef GuestfsProtobufBtrfsFilesystemBalanceArgs guestfs_protobuf_btrfs_filesystem_balance_args;

typedef GuestfsProtobufBtrfsDeviceAddArgs guestfs_protobuf_btrfs_device_add_args;

typedef GuestfsProtobufBtrfsDeviceDeleteArgs guestfs_protobuf_btrfs_device_delete_args;

typedef GuestfsProtobufBtrfsSetSeedingArgs guestfs_protobuf_btrfs_set_seeding_args;

typedef GuestfsProtobufBtrfsFsckArgs guestfs_protobuf_btrfs_fsck_args;

typedef GuestfsProtobufFilesystemAvailableArgs guestfs_protobuf_filesystem_available_args;

typedef GuestfsProtobufFilesystemAvailableRet guestfs_protobuf_filesystem_available_ret;

typedef GuestfsProtobufFstrimArgs guestfs_protobuf_fstrim_args;

typedef GuestfsProtobufDeviceIndexArgs guestfs_protobuf_device_index_args;

typedef GuestfsProtobufDeviceIndexRet guestfs_protobuf_device_index_ret;

typedef GuestfsProtobufNrDevicesRet guestfs_protobuf_nr_devices_ret;

typedef GuestfsProtobufXfsInfoArgs guestfs_protobuf_xfs_info_args;

typedef GuestfsProtobufXfsInfoRet guestfs_protobuf_xfs_info_ret;

typedef GuestfsProtobufPvchangeUuidArgs guestfs_protobuf_pvchange_uuid_args;

typedef GuestfsProtobufVgchangeUuidArgs guestfs_protobuf_vgchange_uuid_args;

typedef GuestfsProtobufUtsnameRet guestfs_protobuf_utsname_ret;

typedef GuestfsProtobufXfsGrowfsArgs guestfs_protobuf_xfs_growfs_args;

typedef GuestfsProtobufRsyncArgs guestfs_protobuf_rsync_args;

typedef GuestfsProtobufRsyncInArgs guestfs_protobuf_rsync_in_args;

typedef GuestfsProtobufRsyncOutArgs guestfs_protobuf_rsync_out_args;

typedef GuestfsProtobufLs0Args guestfs_protobuf_ls0_args;

typedef GuestfsProtobufFillDirArgs guestfs_protobuf_fill_dir_args;

typedef GuestfsProtobufXfsAdminArgs guestfs_protobuf_xfs_admin_args;

typedef GuestfsProtobufHivexOpenArgs guestfs_protobuf_hivex_open_args;

typedef GuestfsProtobufHivexRootRet guestfs_protobuf_hivex_root_ret;

typedef GuestfsProtobufHivexNodeNameArgs guestfs_protobuf_hivex_node_name_args;

typedef GuestfsProtobufHivexNodeNameRet guestfs_protobuf_hivex_node_name_ret;

typedef GuestfsProtobufHivexNodeChildrenArgs guestfs_protobuf_hivex_node_children_args;

typedef GuestfsProtobufHivexNodeChildrenRet guestfs_protobuf_hivex_node_children_ret;

typedef GuestfsProtobufHivexNodeGetChildArgs guestfs_protobuf_hivex_node_get_child_args;

typedef GuestfsProtobufHivexNodeGetChildRet guestfs_protobuf_hivex_node_get_child_ret;

typedef GuestfsProtobufHivexNodeParentArgs guestfs_protobuf_hivex_node_parent_args;

typedef GuestfsProtobufHivexNodeParentRet guestfs_protobuf_hivex_node_parent_ret;

typedef GuestfsProtobufHivexNodeValuesArgs guestfs_protobuf_hivex_node_values_args;

typedef GuestfsProtobufHivexNodeValuesRet guestfs_protobuf_hivex_node_values_ret;

typedef GuestfsProtobufHivexNodeGetValueArgs guestfs_protobuf_hivex_node_get_value_args;

typedef GuestfsProtobufHivexNodeGetValueRet guestfs_protobuf_hivex_node_get_value_ret;

typedef GuestfsProtobufHivexValueKeyArgs guestfs_protobuf_hivex_value_key_args;

typedef GuestfsProtobufHivexValueKeyRet guestfs_protobuf_hivex_value_key_ret;

typedef GuestfsProtobufHivexValueTypeArgs guestfs_protobuf_hivex_value_type_args;

typedef GuestfsProtobufHivexValueTypeRet guestfs_protobuf_hivex_value_type_ret;

typedef GuestfsProtobufHivexValueValueArgs guestfs_protobuf_hivex_value_value_args;

typedef GuestfsProtobufHivexValueValueRet guestfs_protobuf_hivex_value_value_ret;

typedef GuestfsProtobufHivexCommitArgs guestfs_protobuf_hivex_commit_args;

typedef GuestfsProtobufHivexNodeAddChildArgs guestfs_protobuf_hivex_node_add_child_args;

typedef GuestfsProtobufHivexNodeAddChildRet guestfs_protobuf_hivex_node_add_child_ret;

typedef GuestfsProtobufHivexNodeDeleteChildArgs guestfs_protobuf_hivex_node_delete_child_args;

typedef GuestfsProtobufHivexNodeSetValueArgs guestfs_protobuf_hivex_node_set_value_args;

typedef GuestfsProtobufXfsRepairArgs guestfs_protobuf_xfs_repair_args;

typedef GuestfsProtobufXfsRepairRet guestfs_protobuf_xfs_repair_ret;

typedef GuestfsProtobufRmFfArgs guestfs_protobuf_rm_ff_args;

typedef GuestfsProtobufMke2fsArgs guestfs_protobuf_mke2fs_args;

typedef GuestfsProtobufListDiskLabelsRet guestfs_protobuf_list_disk_labels_ret;

typedef GuestfsProtobufInternalHotAddDriveArgs guestfs_protobuf_internal_hot_add_drive_args;

typedef GuestfsProtobufInternalHotRemoveDrivePrecheckArgs guestfs_protobuf_internal_hot_remove_drive_precheck_args;

typedef GuestfsProtobufInternalHotRemoveDriveArgs guestfs_protobuf_internal_hot_remove_drive_args;

typedef GuestfsProtobufMktempArgs guestfs_protobuf_mktemp_args;

typedef GuestfsProtobufMktempRet guestfs_protobuf_mktemp_ret;

typedef GuestfsProtobufMklostAndFoundArgs guestfs_protobuf_mklost_and_found_args;

typedef GuestfsProtobufAclGetFileArgs guestfs_protobuf_acl_get_file_args;

typedef GuestfsProtobufAclGetFileRet guestfs_protobuf_acl_get_file_ret;

typedef GuestfsProtobufAclSetFileArgs guestfs_protobuf_acl_set_file_args;

typedef GuestfsProtobufAclDeleteDefFileArgs guestfs_protobuf_acl_delete_def_file_args;

typedef GuestfsProtobufCapGetFileArgs guestfs_protobuf_cap_get_file_args;

typedef GuestfsProtobufCapGetFileRet guestfs_protobuf_cap_get_file_ret;

typedef GuestfsProtobufCapSetFileArgs guestfs_protobuf_cap_set_file_args;

typedef GuestfsProtobufListLdmVolumesRet guestfs_protobuf_list_ldm_volumes_ret;

typedef GuestfsProtobufListLdmPartitionsRet guestfs_protobuf_list_ldm_partitions_ret;

typedef GuestfsProtobufLdmtoolScanRet guestfs_protobuf_ldmtool_scan_ret;

typedef GuestfsProtobufLdmtoolScanDevicesArgs guestfs_protobuf_ldmtool_scan_devices_args;

typedef GuestfsProtobufLdmtoolScanDevicesRet guestfs_protobuf_ldmtool_scan_devices_ret;

typedef GuestfsProtobufLdmtoolDiskgroupNameArgs guestfs_protobuf_ldmtool_diskgroup_name_args;

typedef GuestfsProtobufLdmtoolDiskgroupNameRet guestfs_protobuf_ldmtool_diskgroup_name_ret;

typedef GuestfsProtobufLdmtoolDiskgroupVolumesArgs guestfs_protobuf_ldmtool_diskgroup_volumes_args;

typedef GuestfsProtobufLdmtoolDiskgroupVolumesRet guestfs_protobuf_ldmtool_diskgroup_volumes_ret;

typedef GuestfsProtobufLdmtoolDiskgroupDisksArgs guestfs_protobuf_ldmtool_diskgroup_disks_args;

typedef GuestfsProtobufLdmtoolDiskgroupDisksRet guestfs_protobuf_ldmtool_diskgroup_disks_ret;

typedef GuestfsProtobufLdmtoolVolumeTypeArgs guestfs_protobuf_ldmtool_volume_type_args;

typedef GuestfsProtobufLdmtoolVolumeTypeRet guestfs_protobuf_ldmtool_volume_type_ret;

typedef GuestfsProtobufLdmtoolVolumeHintArgs guestfs_protobuf_ldmtool_volume_hint_args;

typedef GuestfsProtobufLdmtoolVolumeHintRet guestfs_protobuf_ldmtool_volume_hint_ret;

typedef GuestfsProtobufLdmtoolVolumePartitionsArgs guestfs_protobuf_ldmtool_volume_partitions_args;

typedef GuestfsProtobufLdmtoolVolumePartitionsRet guestfs_protobuf_ldmtool_volume_partitions_ret;

typedef GuestfsProtobufPartSetGptTypeArgs guestfs_protobuf_part_set_gpt_type_args;

typedef GuestfsProtobufPartGetGptTypeArgs guestfs_protobuf_part_get_gpt_type_args;

typedef GuestfsProtobufPartGetGptTypeRet guestfs_protobuf_part_get_gpt_type_ret;

typedef GuestfsProtobufRenameArgs guestfs_protobuf_rename_args;

typedef GuestfsProtobufIsWholeDeviceArgs guestfs_protobuf_is_whole_device_args;

typedef GuestfsProtobufIsWholeDeviceRet guestfs_protobuf_is_whole_device_ret;

typedef GuestfsProtobufInternalParseMountableArgs guestfs_protobuf_internal_parse_mountable_args;

typedef GuestfsProtobufInternalParseMountableRet guestfs_protobuf_internal_parse_mountable_ret;

typedef GuestfsProtobufInternalRhbz914931Args guestfs_protobuf_internal_rhbz914931_args;

typedef GuestfsProtobufFeatureAvailableArgs guestfs_protobuf_feature_available_args;

typedef GuestfsProtobufFeatureAvailableRet guestfs_protobuf_feature_available_ret;

typedef GuestfsProtobufSyslinuxArgs guestfs_protobuf_syslinux_args;

typedef GuestfsProtobufExtlinuxArgs guestfs_protobuf_extlinux_args;

typedef GuestfsProtobufCpRrArgs guestfs_protobuf_cp_rr_args;

typedef GuestfsProtobufRemountArgs guestfs_protobuf_remount_args;

typedef GuestfsProtobufSetUuidArgs guestfs_protobuf_set_uuid_args;

typedef GuestfsProtobufJournalOpenArgs guestfs_protobuf_journal_open_args;

typedef GuestfsProtobufJournalNextRet guestfs_protobuf_journal_next_ret;

typedef GuestfsProtobufJournalSkipArgs guestfs_protobuf_journal_skip_args;

typedef GuestfsProtobufJournalSkipRet guestfs_protobuf_journal_skip_ret;

typedef GuestfsProtobufJournalGetDataThresholdRet guestfs_protobuf_journal_get_data_threshold_ret;

typedef GuestfsProtobufJournalSetDataThresholdArgs guestfs_protobuf_journal_set_data_threshold_args;

typedef GuestfsProtobufAugSetmArgs guestfs_protobuf_aug_setm_args;

typedef GuestfsProtobufAugSetmRet guestfs_protobuf_aug_setm_ret;

typedef GuestfsProtobufAugLabelArgs guestfs_protobuf_aug_label_args;

typedef GuestfsProtobufAugLabelRet guestfs_protobuf_aug_label_ret;

typedef GuestfsProtobufInternalUploadArgs guestfs_protobuf_internal_upload_args;

typedef GuestfsProtobufCopyAttributesArgs guestfs_protobuf_copy_attributes_args;

typedef GuestfsProtobufPartGetNameArgs guestfs_protobuf_part_get_name_args;

typedef GuestfsProtobufPartGetNameRet guestfs_protobuf_part_get_name_ret;

typedef GuestfsProtobufBlkdiscardArgs guestfs_protobuf_blkdiscard_args;

typedef GuestfsProtobufBlkdiscardzeroesArgs guestfs_protobuf_blkdiscardzeroes_args;

typedef GuestfsProtobufBlkdiscardzeroesRet guestfs_protobuf_blkdiscardzeroes_ret;

typedef GuestfsProtobufCpioOutArgs guestfs_protobuf_cpio_out_args;

typedef GuestfsProtobufJournalGetRealtimeUsecRet guestfs_protobuf_journal_get_realtime_usec_ret;

typedef GuestfsProtobufStatnsArgs guestfs_protobuf_statns_args;

typedef GuestfsProtobufStatnsRet guestfs_protobuf_statns_ret;

typedef GuestfsProtobufLstatnsArgs guestfs_protobuf_lstatns_args;

typedef GuestfsProtobufLstatnsRet guestfs_protobuf_lstatns_ret;

typedef GuestfsProtobufInternalLstatnslistArgs guestfs_protobuf_internal_lstatnslist_args;

typedef GuestfsProtobufInternalLstatnslistRet guestfs_protobuf_internal_lstatnslist_ret;


typedef GuestfsProtobufMessageError guestfs_protobuf_message_error;
typedef GuestfsProtobufMessageHeader guestfs_protobuf_message_header;
typedef GuestfsProtobufChunk guestfs_protobuf_chunk;
typedef GuestfsProtobufShmChunk guestfs_protobuf_shm_chunk;
typedef GuestfsProtobufProgress guestfs_protobuf_progress;
typedef GuestfsProtobufFlagMessage guestfs_protobuf_flag_message;

typedef size_t (*protobuf_proc_pack) (ProtobufCMessage *message, uint8_t *out);
typedef ProtobufCMessage* (*protobuf_proc_unpack) (ProtobufCAllocator *allocator, size_t len, const uint8_t *data);

#endif /* _GUESTFS_PROTOBUF_PROTOCOL_TYPEDEFS_H_ */