#ifndef GUESTFS_PROTOCOL_CONSTANTS_H_
#define GUESTFS_PROTOCOL_CONSTANTS_H_

#define PROTOBUF_FLAG_MESSAGE_SIZE 32
#define PROTOBUF_MESSAGE_HEADER_SIZE 64
#define PROTOBUF_PROGRESS_MESSAGE_SIZE 128

#endif /* GUESTFS_PROTOCOL_CONSTANTS_H_ */

