/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: simple.proto */

#ifndef PROTOBUF_C_simple_2eproto__INCLUDED
#define PROTOBUF_C_simple_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Example__ListDevices Example__ListDevices;


/* --- enums --- */

typedef enum _Example__DeviceType {
  EXAMPLE__DEVICE_TYPE__FILE = 1,
  EXAMPLE__DEVICE_TYPE__DEV = 2,
  EXAMPLE__DEVICE_TYPE__NO_TYPE = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EXAMPLE__DEVICE_TYPE)
} Example__DeviceType;

/* --- messages --- */

struct  _Example__ListDevices
{
  ProtobufCMessage base;
  int32_t id;
  char *name;
  ProtobufCBinaryData data;
  size_t n_array;
  int32_t *array;
};
#define EXAMPLE__LIST_DEVICES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&example__list_devices__descriptor) \
    , 0, NULL, {0,NULL}, 0,NULL }


/* Example__ListDevices methods */
void   example__list_devices__init
                     (Example__ListDevices         *message);
size_t example__list_devices__get_packed_size
                     (const Example__ListDevices   *message);
size_t example__list_devices__pack
                     (const Example__ListDevices   *message,
                      uint8_t             *out);
size_t example__list_devices__pack_to_buffer
                     (const Example__ListDevices   *message,
                      ProtobufCBuffer     *buffer);
Example__ListDevices *
       example__list_devices__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   example__list_devices__free_unpacked
                     (Example__ListDevices *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Example__ListDevices_Closure)
                 (const Example__ListDevices *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    example__device_type__descriptor;
extern const ProtobufCMessageDescriptor example__list_devices__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_simple_2eproto__INCLUDED */
