/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: simple.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "simple.pb-c.h"
void   example__list_devices__init
                     (Example__ListDevices         *message)
{
  static Example__ListDevices init_value = EXAMPLE__LIST_DEVICES__INIT;
  *message = init_value;
}
size_t example__list_devices__get_packed_size
                     (const Example__ListDevices *message)
{
  assert(message->base.descriptor == &example__list_devices__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t example__list_devices__pack
                     (const Example__ListDevices *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &example__list_devices__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t example__list_devices__pack_to_buffer
                     (const Example__ListDevices *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &example__list_devices__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Example__ListDevices *
       example__list_devices__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Example__ListDevices *)
     protobuf_c_message_unpack (&example__list_devices__descriptor,
                                allocator, len, data);
}
void   example__list_devices__free_unpacked
                     (Example__ListDevices *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &example__list_devices__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor example__list_devices__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Example__ListDevices, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Example__ListDevices, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Example__ListDevices, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "array",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Example__ListDevices, n_array),
    offsetof(Example__ListDevices, array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned example__list_devices__field_indices_by_name[] = {
  3,   /* field[3] = array */
  2,   /* field[2] = data */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange example__list_devices__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor example__list_devices__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "example.ListDevices",
  "ListDevices",
  "Example__ListDevices",
  "example",
  sizeof(Example__ListDevices),
  4,
  example__list_devices__field_descriptors,
  example__list_devices__field_indices_by_name,
  1,  example__list_devices__number_ranges,
  (ProtobufCMessageInit) example__list_devices__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue example__device_type__enum_values_by_number[3] =
{
  { "FILE", "EXAMPLE__DEVICE_TYPE__FILE", 1 },
  { "DEV", "EXAMPLE__DEVICE_TYPE__DEV", 2 },
  { "NO_TYPE", "EXAMPLE__DEVICE_TYPE__NO_TYPE", 5 },
};
static const ProtobufCIntRange example__device_type__value_ranges[] = {
{1, 0},{5, 2},{0, 3}
};
static const ProtobufCEnumValueIndex example__device_type__enum_values_by_name[3] =
{
  { "DEV", 1 },
  { "FILE", 0 },
  { "NO_TYPE", 2 },
};
const ProtobufCEnumDescriptor example__device_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "example.DeviceType",
  "DeviceType",
  "Example__DeviceType",
  "example",
  3,
  example__device_type__enum_values_by_number,
  3,
  example__device_type__enum_values_by_name,
  2,
  example__device_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
