#!/bin/bash

GENERATOR_NAME=generator
GENERATOR_DIR_NAME=generator
LIBGUESTFS_DIR_NAME=libguestfs-1.28.5
PROTO_FILE_NAME=guestfs_protocol.proto
DEST_PROTO_DIR_NAME=test-proto

cd ..
cp -r $GENERATOR_DIR_NAME $LIBGUESTFS_DIR_NAME
cd $LIBGUESTFS_DIR_NAME
./$GENERATOR_DIR_NAME/$GENERATOR_NAME
cd ..
cp $LIBGUESTFS_DIR_NAME/src/$PROTO_FILE_NAME $GENERATOR_DIR_NAME/$DEST_PROTO_DIR_NAME/$PROTO_FILE_NAME
chmod 0664 $GENERATOR_DIR_NAME/$DEST_PROTO_DIR_NAME/$PROTO_FILE_NAME
